name: gameio
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #google dependencies
  google_maps_flutter: ^2.0.3
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  age: ^0.0.1

  #firebase dependencies
  firebase_core: ^1.4.0
  firebase_auth: ^3.11.2
  firebase_storage: ^10.0.1



  permission_handler:

  provider: ^6.0.4


  cupertino_icons: ^1.0.0
  geolocator: ^9.0.2
  image_picker: ^0.8.0+3
  cloud_firestore: ^3.5.1
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  geoflutterfire: ^3.0.1
  flutter_markdown: ^0.6.6
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/map_style.txt
    - assets/images/
    - assets/


  fonts:
    - family: JuliusSansOne
      fonts:
        - asset: fonts/JuliusSansOne-Regular.ttf
